language: perl
perl:
  - "5.30"
  - "5.28"
  - "5.26"
services:
  - postgresql
addons:
  apt:
    packages:
      - libcache-perl
      - libdb-dev
      - libpq-dev
      - libxml2-dev
  postgresql: "11"
before_script:
  - cp .travis.travelynx.conf travelynx.conf
  - psql -c 'create database travelynx_ci_test;' -U postgres
script:
  - prove -lv
