language: perl
perl:
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20"
services:
  - postgresql
addons:
  apt:
    packages:
      - libcache-perl
      - libdb-dev
      - libpq-dev
      - libxml2-dev
before_script:
  - cp .travis.travelynx.conf travelynx.conf
  - psql -c 'create database travelynx_ci_test;' -U postgres
script:
  - carton install
  - carton exec prove -lv
