version: "3.6"
x-common-env: &common-env
  TRAVELYNX_DB_HOST: database
  TRAVELYNX_DB_NAME: travelynx
  TRAVELYNX_DB_USERNAME: travelynx
  TRAVELYNX_DB_PASSWORD: travelynx
services:
  database:
    image: postgres:11
    networks:
      - backend
    environment: 
      <<: *common-env
    volumes:
      - ./examples/docker/postgres-init.sh:/docker-entrypoint-initdb.d/init.sh
  travelynx:
    build: .
    ports:
      - "8000:8093"
    networks:
      - backend
    volumes:
      - ./examples/docker/travelynx.conf:/app/travelynx.conf
    environment:
      <<: *common-env
      TRAVELYNX_MAIL_DISABLE: 1
      TRAVELYNX_SECRET: 12345678
networks:
  backend:
